openapi: 3.1.0

info:
  title: Stripe Accounts API
  version: "2024-01-01"
  description: |
    Accounts represent entities on Stripe, including businesses and individuals.
    This API allows you to create, retrieve, update, list, and close accounts.

servers:
  - url: https://api.stripe.com/v1
    description: Stripe API base URL

tags:
  - name: Accounts
    description: Create and manage accounts

paths:
  /accounts:
    get:
      tags: [Accounts]
      summary: List accounts
      operationId: listAccounts
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            example: 10
        - in: query
          name: starting_after
          schema:
            type: string
            example: acct_123
      responses:
        "200":
          description: A paginated list of accounts
          content:
            application/json:
              examples:
                default:
                  summary: List response
                  value:
                    object: list
                    data:
                      - id: acct_123
                        object: account
                        type: standard
                        country: US
                        email: owner@example.com
                        created: 1710000000
                    has_more: false
              schema:
                $ref: "#/components/schemas/AccountList"

    post:
      tags: [Accounts]
      summary: Create an account
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/AccountCreateParams"
      responses:
        "200":
          description: Account created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"

  /accounts/{account_id}:
    get:
      tags: [Accounts]
      summary: Retrieve an account
      operationId: retrieveAccount
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
            example: acct_123
      responses:
        "200":
          description: Account object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"

    post:
      tags: [Accounts]
      summary: Update an account
      operationId: updateAccount
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
            example: acct_123
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/AccountUpdateParams"
      responses:
        "200":
          description: Account updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"

    delete:
      tags: [Accounts]
      summary: Close an account
      operationId: closeAccount
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
            example: acct_123
      responses:
        "200":
          description: Account closed
          content:
            application/json:
              examples:
                default:
                  value:
                    id: acct_123
                    object: account
                    deleted: true
              schema:
                type: object
                properties:
                  id:
                    type: string
                  object:
                    type: string
                  deleted:
                    type: boolean

components:
  schemas:
    Account:
      type: object
      required:
        - id
        - object
        - type
        - country
        - created
      properties:
        id:
          type: string
          example: acct_123
        object:
          type: string
          example: account
        type:
          type: string
          enum: [standard, express, custom]
          example: standard
        country:
          type: string
          example: US
        email:
          type: string
          example: owner@example.com
        charges_enabled:
          type: boolean
          example: true
        payouts_enabled:
          type: boolean
          example: true
        created:
          type: integer
          example: 1710000000

    AccountList:
      type: object
      required: [object, data, has_more]
      properties:
        object:
          type: string
          example: list
        data:
          type: array
          items:
            $ref: "#/components/schemas/Account"
        has_more:
          type: boolean
          example: false

    AccountCreateParams:
      type: object
      required: [type]
      properties:
        type:
          type: string
          enum: [standard, express, custom]
          example: express
        country:
          type: string
          example: US
        email:
          type: string
          example: owner@example.com

    AccountUpdateParams:
      type: object
      properties:
        email:
          type: string
          example: updated@example.com
        business_profile[mcc]:
          type: string
          example: "5734"

    AccountEventType:
      type: string
      enum:
        - account.created
        - account.updated
        - account.external_account.created
        - account.external_account.deleted
        - account.application.authorized
        - account.application.deauthorized